apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
spec:
  project: default
  source:
    repoURL: 
    path: /
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
